import 'package:flutter/material.dart';
import '../cards/searchBar.dart';
import '../../models/lecturer.dart';
import '../popup/add_lecturer_popup.dart';
import '../../hooks/use_lectureres.dart';

class LecturersPage extends StatefulWidget {
  const LecturersPage({super.key});

  @override
  State<LecturersPage> createState() => _LecturersPageState();
}

class _LecturersPageState extends State<LecturersPage> {
  final UseTeachers _useTeachers = UseTeachers();
  List<Teacher> _teachers = [];
  bool _loading = false;
  String _searchText = '';
  int? _selectedIndex;
  String? _error;

  List<Teacher> get _filteredTeachers => _teachers
      .where(
        (teacher) =>
            teacher.id.toLowerCase().contains(_searchText.toLowerCase()) ||
            (teacher.teacherName ?? '').toLowerCase().contains(
              _searchText.toLowerCase(),
            ),
      )
      .toList();

  @override
  void initState() {
    super.initState();
    _fetchTeachers();
  }

  Future<void> _fetchTeachers() async {
    setState(() {
      _loading = true;
      _error = null;
    });
    try {
      final teachers = await _useTeachers.fetchTeachers();
      setState(() {
        _teachers = teachers;
        _loading = false;
        _selectedIndex = null;
      });
    } catch (e) {
      setState(() {
        _loading = false;
        _error = 'Error fetching teachers';
      });
    }
  }

  Future<void> _showAddLecturerPopup() async {
    final result = await showDialog<Lecturer>(
      context: context,
      builder: (context) => const AddLecturerPopup(),
    );
    if (result != null) {
      final teacher = Teacher(
        id: '', // id will be generated by DB
        username: result.id,
        teacherName: result.name,
        password: result.password,
        createdAt: DateTime.now(),
      );
      await _useTeachers.addTeacher(teacher);
      await _fetchTeachers();
    }
  }

  Future<void> _showEditLecturerPopup() async {
    if (_selectedIndex == null) return;
    final teacher = _filteredTeachers[_selectedIndex!];
    final lecturer = Lecturer(
      id: teacher.username ?? '',
      name: teacher.teacherName ?? '',
      password: teacher.password ?? '',
    );
    final result = await showDialog<Lecturer>(
      context: context,
      builder: (context) => AddLecturerPopup(lecturer: lecturer),
    );
    if (result != null) {
      final updatedTeacher = Teacher(
        id: teacher.id,
        username: result.id,
        teacherName: result.name,
        password: result.password,
        createdAt: teacher.createdAt,
      );
      await _useTeachers.updateTeacher(teacher.id, updatedTeacher);
      await _fetchTeachers();
    }
  }

  Future<void> _confirmDeleteLecturer() async {
    if (_selectedIndex == null) return;
    final teacher = _filteredTeachers[_selectedIndex!];
    final confirm = await showDialog<bool>(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text("Delete Lecturer"),
        content: Text(
          "Are you sure you want to delete '${teacher.teacherName}'?",
        ),
        actions: [
          TextButton(
            onPressed: () => Navigator.of(context).pop(false),
            child: const Text("Cancel"),
          ),
          ElevatedButton(
            onPressed: () => Navigator.of(context).pop(true),
            style: ElevatedButton.styleFrom(backgroundColor: Colors.red),
            child: const Text("Delete"),
          ),
        ],
      ),
    );
    if (confirm == true) {
      await _useTeachers.deleteTeacher(teacher.id);
      await _fetchTeachers();
    }
  }

  void _handleRowTap(int index) {
    setState(() {
      _selectedIndex = index;
    });
  }

  @override
  Widget build(BuildContext context) {
    final double screenWidth = MediaQuery.of(context).size.width;
    final bool isDesktop = screenWidth > 800;

    return Padding(
      padding: const EdgeInsets.all(32.0),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const SizedBox(height: 8),
          const Text(
            "Lecturers",
            style: TextStyle(
              fontSize: 28,
              fontWeight: FontWeight.bold,
              color: Colors.black87,
            ),
          ),
          const SizedBox(height: 24),
          if (_loading) const Center(child: CircularProgressIndicator()),
          if (_error != null)
            Center(
              child: Text(_error!, style: const TextStyle(color: Colors.red)),
            ),
          if (!_loading && _error == null)
            Row(
              crossAxisAlignment: CrossAxisAlignment.start,
              children: [
                Expanded(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      SearchAddBar(
                        hintText: "Search Lecturer...",
                        buttonText: "Add Lecturer",
                        onAddPressed: _showAddLecturerPopup,
                        onChanged: (value) {
                          setState(() {
                            _searchText = value;
                            _selectedIndex = null;
                          });
                        },
                      ),
                      const SizedBox(height: 16),
                      Row(
                        mainAxisAlignment: MainAxisAlignment.end,
                        children: [
                          SizedBox(
                            width: 80,
                            height: 36,
                            child: ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.green,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(18),
                                ),
                                padding: const EdgeInsets.symmetric(
                                  vertical: 0,
                                  horizontal: 0,
                                ),
                              ),
                              onPressed: _selectedIndex == null
                                  ? null
                                  : _showEditLecturerPopup,
                              child: const Text(
                                "Edit",
                                style: TextStyle(
                                  fontSize: 15,
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                          const SizedBox(width: 8),
                          SizedBox(
                            width: 80,
                            height: 36,
                            child: ElevatedButton(
                              style: ElevatedButton.styleFrom(
                                backgroundColor: Colors.red,
                                shape: RoundedRectangleBorder(
                                  borderRadius: BorderRadius.circular(18),
                                ),
                                padding: const EdgeInsets.symmetric(
                                  vertical: 0,
                                  horizontal: 0,
                                ),
                              ),
                              onPressed: _selectedIndex == null
                                  ? null
                                  : _confirmDeleteLecturer,
                              child: const Text(
                                "Delete",
                                style: TextStyle(
                                  fontSize: 15,
                                  color: Colors.white,
                                ),
                              ),
                            ),
                          ),
                        ],
                      ),
                    ],
                  ),
                ),
              ],
            ),
          const SizedBox(height: 8),
          if (!_loading && _error == null)
            Expanded(
              child: Container(
                width: double.infinity,
                color: Colors.transparent,
                child: isDesktop
                    ? _buildDesktopTable()
                    : SingleChildScrollView(
                        scrollDirection: Axis.vertical,
                        child: SingleChildScrollView(
                          scrollDirection: Axis.horizontal,
                          child: _buildMobileTable(),
                        ),
                      ),
              ),
            ),
        ],
      ),
    );
  }

  Widget _buildDesktopTable() {
    return Table(
      columnWidths: const {
        0: FixedColumnWidth(64), // No
        1: FixedColumnWidth(140), // Lecturer ID
        2: FixedColumnWidth(140), // Lecturer Name
      },
      border: TableBorder(
        horizontalInside: BorderSide(color: Colors.grey.shade300),
      ),
      children: [
        TableRow(
          children: [
            _tableHeaderCell("No"),
            _tableHeaderCell("Lecturer ID"),
            _tableHeaderCell("Lecturer Name"),
          ],
        ),
        for (int index = 0; index < _filteredTeachers.length; index++)
          TableRow(
            decoration: BoxDecoration(
              color: _selectedIndex == index
                  ? Colors.blue.shade50
                  : Colors.transparent,
            ),
            children: [
              _tableBodyCell('${index + 1}', onTap: () => _handleRowTap(index)),
              _tableBodyCell(
                _filteredTeachers[index].username ?? '',
                onTap: () => _handleRowTap(index),
              ),
              _tableBodyCell(
                _filteredTeachers[index].teacherName ?? '',
                onTap: () => _handleRowTap(index),
              ),
            ],
          ),
      ],
    );
  }

  Widget _buildMobileTable() {
    return Table(
      defaultColumnWidth: const IntrinsicColumnWidth(),
      border: TableBorder(
        horizontalInside: BorderSide(color: Colors.grey.shade300),
      ),
      children: [
        TableRow(
          children: [
            _tableHeaderCell("No"),
            _tableHeaderCell("Lecturer ID"),
            _tableHeaderCell("Lecturer Name"),
          ],
        ),
        for (int index = 0; index < _filteredTeachers.length; index++)
          TableRow(
            decoration: BoxDecoration(
              color: _selectedIndex == index
                  ? Colors.blue.shade50
                  : Colors.transparent,
            ),
            children: [
              _tableBodyCell('${index + 1}', onTap: () => _handleRowTap(index)),
              _tableBodyCell(
                _filteredTeachers[index].username ?? '',
                onTap: () => _handleRowTap(index),
              ),
              _tableBodyCell(
                _filteredTeachers[index].teacherName ?? '',
                onTap: () => _handleRowTap(index),
              ),
            ],
          ),
      ],
    );
  }

  Widget _tableHeaderCell(String text) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 16, horizontal: 16),
      child: Text(
        text,
        style: const TextStyle(fontWeight: FontWeight.bold),
        textAlign: TextAlign.left,
        overflow: TextOverflow.ellipsis,
      ),
    );
  }

  Widget _tableBodyCell(String text, {VoidCallback? onTap}) {
    return InkWell(
      onTap: onTap,
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 12, horizontal: 16),
        child: Text(text, overflow: TextOverflow.ellipsis),
      ),
    );
  }
}
